name: learn github actions

on:
  push:
    branches: [ "master", "development" ]
  pull_request:
    branches: [ master ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: check disc space
      run: df
    - uses : actions/checkout@v3
    - name: setup jdk
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: '11'
    - name: build with maven
      run: mvn -B package --file pom.xml
    - name: log build tool version
      run: |
        mvn --version
        gradle --version
        ant -version
        git --version
    - name: log disc space
      run: df
        
    
    
