name: learn github actions

on:
  push:
    branches: [ master development ]
  pull_request:
    branches: [ master ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: run a oneline script
      run : echo hello, world !
      
    - name: run a multiline script
      run: 
        what is in the directory ?
        ls -a
        echo
        echo is java installed ?
        java -version
        echo
        echo is git installed ?
        git --version
        echo what about build tools
        mvn --version
        gradle --version
        ant -version
      
    
    
